import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const contentDir = path.resolve(__dirname, 'src/wiki-content');
function wikiPlugin(){const V='virtual:wiki-content',R='\0'+V;
function loadAll(ctx){let files=[];try{files=fs.readdirSync(contentDir).filter(f=>f.endsWith('.md'))}catch{}const pages={};for(const f of files){const fp=path.join(contentDir,f);ctx?.addWatchFile?.(fp);pages[`/src/wiki-content/${f}`]=fs.readFileSync(fp,'utf-8')}return pages}
function addMiddleware(server){server.middlewares.use((req,res,next)=>{
if(req.method==='GET'&&req.url.startsWith('/pages/')&&req.url.endsWith('.md')){const fname=req.url.split('/').pop();const file=path.join(contentDir,fname);try{res.writeHead(200,{'Content-Type':'text/plain;charset=utf-8'});res.end(fs.readFileSync(file,'utf-8'));return}catch{const distFile=path.resolve(__dirname,'dist','pages',fname);try{res.writeHead(200,{'Content-Type':'text/plain;charset=utf-8'});res.end(fs.readFileSync(distFile,'utf-8'));return}catch{}}res.writeHead(404);res.end('Not found');return}
if(req.method==='POST'&&req.url==='/api/save'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const{slug,lang,content}=JSON.parse(body);const safe=slug.replace(/[^a-zA-Z0-9_-]/g,'');const file=path.join(contentDir,`${safe}.${lang}.md`);fs.writeFileSync(file,content,'utf-8');const distFile=path.resolve(__dirname,'dist','pages',`${safe}.${lang}.md`);try{fs.mkdirSync(path.dirname(distFile),{recursive:true});fs.copyFileSync(file,distFile)}catch{}const verified=fs.readFileSync(file,'utf-8')===content;console.log(`  💾 Saved: ${safe}.${lang}.md  (${content.length}B, verified=${verified})`);res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:true,file:`${safe}.${lang}.md`,verified}))}catch(e){console.error('  ❌ Save:',e.message);res.writeHead(400,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:e.message}))}});return}
if(req.method==='DELETE'&&req.url==='/api/page'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const{slug,lang}=JSON.parse(body);const safe=slug.replace(/[^a-zA-Z0-9_-]/g,'');const file=path.join(contentDir,`${safe}.${lang}.md`);if(fs.existsSync(file))fs.unlinkSync(file);const distFile=path.resolve(__dirname,'dist','pages',`${safe}.${lang}.md`);if(fs.existsSync(distFile))fs.unlinkSync(distFile);console.log(`  🗑 Deleted: ${safe}.${lang}.md`);res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:true}))}catch(e){console.error('  ❌ Delete:',e.message);res.writeHead(400,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:e.message}))}});return}
next()})}
return{name:'wiki',resolveId(id){if(id===V)return R},load(id){if(id===R)return`const data=${JSON.stringify(loadAll(this))};export default data;`},configureServer:addMiddleware,configurePreviewServer:addMiddleware}}
function emitPlugin(){let cfg={};return{name:'emit',async buildStart(){try{cfg=await import(path.resolve(__dirname,'src/config.js'))}catch{}},async closeBundle(){const dist=path.resolve(__dirname,'dist');const pagesDir=path.join(dist,'pages');fs.mkdirSync(pagesDir,{recursive:true});let files=[];try{files=fs.readdirSync(contentDir).filter(f=>f.endsWith('.md'))}catch{}for(const f of files)fs.copyFileSync(path.join(contentDir,f),path.join(pagesDir,f));const hash=cfg.ADMIN_PASSWORD?crypto.createHash('sha256').update(cfg.ADMIN_PASSWORD).digest('hex'):'';const out={admin:{username:cfg.ADMIN_USERNAME||'root',passwordHash:hash},defaultLanguage:cfg.DEFAULT_LANGUAGE||'fa',languages:cfg.LANGUAGES||['fa','en'],homePage:cfg.HOME_PAGE||'home',title:cfg.SITE_TITLE||{fa:'ویکی زمردین',en:'Emerald Wiki'}};fs.writeFileSync(path.join(dist,'config.js'),`(function(){window.__EMERALD_CONFIG__=${JSON.stringify(out)};})();`);const idx=path.join(dist,'index.html');let html=fs.readFileSync(idx,'utf-8');html=html.replace('</head>','  <script src="./config.js" defer></script>\n  </head>');fs.writeFileSync(idx,html);console.log(`  ✅ dist/config.js   (password → SHA‑256 hash)`);console.log(`  ✅ dist/pages/      (${files.length} .md files)`)}}}
function fileProtocolPlugin(){return{name:'file-protocol',transformIndexHtml:{order:'post',handler(h){return h.replace(/type="module"/g,'defer').replace(/\scrossorigin(?:="[^"]*")?/g,'')}}}}
export default defineConfig({plugins:[svelte(),wikiPlugin(),emitPlugin(),fileProtocolPlugin()],base:'./',build:{outDir:'dist',assetsDir:'assets',cssCodeSplit:false,minify:'esbuild',rollupOptions:{output:{format:'iife',inlineDynamicImports:true,manualChunks:undefined}}}});